/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      spacing: {
        "container-padding-mobile": "1.5rem",
        "container-padding-desktop": "4rem",
      },
      colors: {
        "error": "#ffb4ab",
        "on-primary-container": "#5d6b00",
        "surface": "#131313",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d2f000",
        "on-secondary": "#480081",
        "surface-tint": "#b8d300",
        "background": "#131313",
        "on-primary": "#2c3400",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#006f77",
        "on-surface-variant": "#c6c9ab",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#414c00",
        "tertiary-container": "#7df4ff",
        "on-tertiary": "#00363a",
        "secondary-fixed": "#efdbff",
        "surface-container-lowest": "#0e0e0e",
        "outline": "#909378",
        "inverse-primary": "#576500",
        "secondary-container": "#7701d0",
        "on-tertiary-fixed-variant": "#004f54",
        "on-primary-fixed": "#191e00",
        "on-secondary-container": "#dcb7ff",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#2c0051",
        "on-error": "#690005",
        "secondary-fixed-dim": "#dcb8ff",
        "primary": "#ffffff",
        "secondary": "#dcb8ff",
        "surface-dim": "#131313",
        "tertiary": "#ffffff",
        "tertiary-fixed-dim": "#00dbe9",
        "on-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface-container": "#201f1f",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed": "#002022",
        "primary-fixed-dim": "#b8d300",
        "surface-bright": "#3a3939",
        "primary-container": "#d2f000",
        "inverse-on-surface": "#313030",
        "outline-variant": "#454932",
        "tertiary-fixed": "#7df4ff",
        "surface-container-highest": "#353534",
        "on-secondary-fixed-variant": "#6700b5",
        "on-background": "#e5e2e1"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Outfit"],
        "headline-md": ["Outfit"],
        "display-lg": ["Outfit"],
        "label-caps": ["JetBrains Mono"],
        "headline-lg": ["Outfit"],
        "display-md": ["'Space Grotesk'", "sans-serif"]
      }
    },
  },
  plugins: [],
}
